### ISSUE TITLE
Deprecated function connecting to SACC

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/firecrown#126]
I'm getting this error in generate_srd_data.py. It looks like it's trying to call some deprecated function.

> python generate_srd_data.py
> Traceback (most recent call last):
>   File "Documents/lsst_augur/firecrown/examples/desc_srd_v1/generate_srd_data.py", line 3, in <module>
>     from firecrown.ccl.two_point import build_sacc_data
> ImportError: cannot import name 'build_sacc_data' from 'firecrown.ccl.two_point' (Documents/lsst_augur/firecrown/firecrown/ccl/two_point.py)

**Comment by marcpaterno** [comment]
It appears the import should be:

    from fire crown.ccl._ccl import build_sacc_data

With that change, the import works for me. However, running the script (from the directory `firecrown/examples/desc_srd_v1`) fails because `firecrown.compute_loglike(cosmo=cosmo, data=data)` returns only one value, and the code calling it (`firecrown/examples/desc_srd_v1/generate_srd_data.py", line 10`) is expecting two values.

**Comment by elisachisari** [comment]
Ok, I think this would also be happening in the "generate" function in augur: https://github.com/LSSTDESC/augur/blob/master/augur/generate.py 
but maybe @fjaviersanchez already fixed it there.

**Comment by vitenti** [comment]
Made irrelevant by PR #181
