### ISSUE TITLE
Push more functionality down into MappingCosmoSIS

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/firecrown#148]
The current implementation of the CosmoSIS module's `execute` function does much work by reaching into and manipulating the innards of the mapping object. This work should be delegated to the `MappingCosmoSIS` class, in preparation for another refactoring in which the appropriate work will be lifted up to the `Mapping` base class, to be shared with the Cobaya connector.

**Comment by vitenti** [comment]
I just created a new branch and PR fixing this issue. I had also to modify the caching code for the traces since they used the params to create a hash, now it only uses the CCL cosmology object. Instead of hashing the parameters, now every time _update is called it automatically erases the cache, that is, we need new tracers when in a different point of the parametric space.
