### ISSUE TITLE
Installation instruction issues from August 2022 collaboration meeting

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/firecrown#172]
Please add here any issues you have run into when (trying to) follow the Firecrown installation instructions.

**Comment by shuang92** [comment]
Hi everyone, I met this error while trying to compile the cosmosis standard library following the instruction.

$ cosmosis-build-standard-library

error in output:

interface_tools.f90:49:99:

   49 |                     status = status + datablock_get_double_grid(block, cdm_baryon_power_lin_section, &
      |                                                                                                   1
Error: Symbol 'cdm_baryon_power_lin_section' at (1) has no IMPLICIT type; did you mean 'gal_matter_power_lin_section'?
compute_mf_tinker.f90:10:6:

   10 |   USE interface_tools
      |      1
Fatal Error: Cannot open module file 'interface_tools.mod' for reading at (1): No such file or directory
compilation terminated.
tinker_module.F90:4:5:

    4 |  USE interface_tools
      |     1
Fatal Error: Cannot open module file 'interface_tools.mod' for reading at (1): No such file or directory

I'm installing locally on an archlinux environment. A temporary fix was suggested by @tilmantroester to clone the library instead of compiling:

git clone github.com:joezuntz/cosmosis-standard-library
or
git clone http://github.com/joezuntz/cosmosis-standard-library

**Comment by agnesemenaite** [comment]
Not exactly an installation issue, but related to confusing error messages when running Firecrown for the first time without having set {FIRECROWN_DIR} to point to the correct directory. The final error message seen by the user is distracting from the actual issue.

Here when running "cobaya-run cobaya_evaluate.yaml" (but apparently also applicable to cosmosis):

<...>
```
FileNotFoundError: [Errno 2] No such file or directory: '${FIRECROWN_DIR}/examples/des_y1_3x2pt/des_y1_3x2pt_sacc_data.fits'
The above exception was the direct cause of the following exception:
```
<...>
```
 File "/Users/agne/opt/anaconda3/envs/fc/lib/python3.10/site-packages/firecrown/likelihood/likelihood.py", line 105, in load_likelihood
    raise ImportError(f"{e.strerror}: {filename}") from e
ImportError: No such file or directory: des_y1_3x2pt.py
```

**Comment by agnesemenaite** [comment]
Additionally, currently "Installation Quickstart" (https://firecrown.readthedocs.io/en/latest/install_quick.html) has, as the first suggested installation option "conda create --name fc -c conda-forge firecrown" described as 

"This will install Firecrown as well as the samplers that are currently supported." 

In reality, the supported samplers (cobaya and cosmosis) still need to be installed separately.

**Comment by marcpaterno** [comment]
> Additionally, currently "Installation Quickstart" (https://firecrown.readthedocs.io/en/latest/install_quick.html) has, as the first suggested installation option "conda create --name fc -c conda-forge firecrown" described as
> 
> "This will install Firecrown as well as the samplers that are currently supported."
> 
> In reality, the supported samplers (cobaya and cosmosis) still need to be installed separately.

We have learned from this and other feedback that the warning box was not sufficient to alert readers that this part of the instructions indicated what we intended to support, but was not yet working. We'll be removing the instructions that do not yet work and add them back when they are working.
