### ISSUE TITLE
Treatment and constrains on systematics parameters

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/firecrown#246]
I created a synthetic cosmic shear data vector (5 redshift bins) with some NLA amplitude for alignments. 
I am analysing it with firecrown with my own Gaussian covariance.
I want to see if I recover the right Omega_m and NLA amplitude.
I have two questions about this:
1) Is each tracer NLA amplitude assumed to be independent? If yes, is there a way to assume them to be the same?
2) Where can I find the output of the constraints on the NLA amplitude?

**Comment by tilmantroester** [comment]
1. If the systematic is defined without specifying `sacc_tracer`, like in https://github.com/LSSTDESC/firecrown/blob/master/examples/des_y1_3x2pt/des_y1_3x2pt.py#L19, then the parameters are the same for all tracers the systematic is applied to.
2. The IA parameter is set like this: https://github.com/LSSTDESC/firecrown/blob/master/examples/des_y1_3x2pt/des_y1_3x2pt_values.ini#L25. Since it's being sampled, it will be in the chain output. Derived parameters are supported in principle but not implemented yet in practice.
