### ISSUE TITLE
Make cluster abundance an independent module with a connector for firecrown

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/firecrown#297]

**Comment by marcpaterno** [comment]
The title of this issue does not make it clear to me what problem is being addressed. Can you please clarify the problem?

**Comment by marcpaterno** [comment]
That helps, but it still seems to me that this is a proposed solution rather than a specification of a problem to be solved. What is the reason for (eventually) moving this code outside of the firecrown repository? The answer to that question will help determine the right way to go about doing it.

**Comment by mattkwiecien** [comment]
To summarize some of our discussion from last week.  The cluster abundance calculations are being done in multiple different packages (`Augur` for forecasting, `TJPCov` for abundance covariance, `Firecrown` for the likelihood).  To ensure consistency between these packages, we're trying to create some independent module that can be accessed by the other tools.  

Because the abundance models are not purely theoretical predictions but also include phenomenological models, such as selection functions for our various cluster finders, `CCL` isn't quite a good fit for this code either.

@m-aguena we discussed taking the following approach, but still thinking through/prototyping:
* Creating a cluster likelihood factory function that builds the cluster theoretical model.  This would be in the new external module.  
* This factory function could then be used by `Augur`, `TJPCov`, `Firecrown` along with something similar to an .ini file that configures the theoretical model.
* `ModelingTools` in Firecrown could then load the cluster abundance likelihood from the external factory function (location TBD), and populate all models in firecrown with a consistent model / cosmology.
