### ISSUE TITLE
Updating `setup.py`

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/firecrown#322]
### Discussed in https://github.com/LSSTDESC/firecrown/discussions/318

<div type='discussions-op-text'>

<sup>Originally posted by **am610** September 24, 2023</sup>
the `setup.py` code has these following lines, which I want to confirm wether correct:
1. 
```
with open(pth, "r") as fp:
    start = False
    for line in fp.readlines():
        if line.strip() == "dependencies:":
            start = False
        if start:
              ...

```

The variable `start` is meant to be a flag that determines when the script should start reading the dependencies from the environment.yml file ?  However, it is initialized to False and is never set to True. Additionally, there’s a line that incorrectly sets start back to False when the script encounters the "dependencies:" line, instead of setting it to True. Is this correct ?

2. In the `_munge_req` function: 
`for sym in ["~", "=", "<", ">", ",", "!", "!"]:
`
The "!" symbol is listed twice in the list. This is not redundant ?

3. `r = line.strip()[3:].strip()`
why this first 3 letters stripping ?</div>

**Comment by vitenti** [comment]
In PR #324, I made improvements by moving all configuration to `setup.cfg` from `setup.py`. This change is an initial step before transitioning to `pyproject.toml`. However, considering that the latter change would necessitate a modification in our installation instructions, I suggest leaving it for a separate PR.

Additionally, I've started investigating "Strict editable installs," which could allow us to modify our instructions to use it instead of the current method involving `python setup.py build` and `export PYTHONPATH=`.
