### ISSUE TITLE
Save predictions to sacc

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/firecrown#346]
A common use case is producing model predictions and then using those prediction as mock data for some downstream tasks. For that the model predictions need to be saved to a sacc object, for which the functionality does not yet exist in firecrown.

There are multiple implementations of this floating around in DESC (e.g. TXPipe, augur, as well as a number of notebooks), standardising one implementation in firecrown would reduce the overall maintenance burden across the various projects that rely on this functionality.

**Comment by vitenti** [comment]
If we understood correctly your request and your PR, the additional information that would be necessary to use a computed theory vector to update a SACC object would be the list of indices. In this case we can save the SACC indices inside likelihood and have a method to return it. Thus, we can create a separate function that take SACC, theory vector and indices as input and update the SACC object. What do you think about this solution, since updating the SACC object is not part of the likelihood workflow we think that a separated function would be easier to test. We have however a question:

- In the PR you saved the last computed theory vector to use in the SACC update, is there a reason for that (will it take place during a full MCMC)? Otherwise, it is simpler to keep these separated, otherwise we need to make sure that the cached quantities are invalidated at the correct time.

**Comment by tilmantroester** [comment]
This could be done in a separate function as well. My reason for putting it in `Likelihood` is that this allows access to the setup of the statistics and their internal state. For example to allow more sophisticated checking of which parts of the data vector are being saved.
I don't think assuming a specific workflow is a good approach here. Different users have different workflows. For example, the current design around a sampling workflow is ill-suited for a modelling workflow, which is already causing problems.

As for the issue with the caching: firecrown already caches the predictions (at least for two-point stats) and uses them downstream, `get_theory_vector` just gives a proper API for this. This is useful whenever you want to do anything beyond computing the chi2, such as plotting or saving the predictions.
firecrown has a very stateful design, so this doesn't seem out of place to me.

**Comment by tilmantroester** [comment]
This has been addressed with #390 and #349.
