### ISSUE TITLE
Theoretical prediction breaking with certain bandpower windows

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/firecrown#368]
When including bandpower windows, `_ell_for_xi` is used to compute the ell values to compute the cached power spectrum, but in certain situations it can return repeated integer values, which breaks things in `compute_theory_vector` since CCL requires the ell array to be monotonically increasing. The quick workaround would be to change this line: https://github.com/LSSTDESC/firecrown/blob/master/firecrown/likelihood/gauss_family/statistic/two_point.py#L54 to `np.unique(np.around(concatenated))`

**Comment by marcpaterno** [comment]
To make sure the fix is complete, we will add type annotations to the method in question to make sure that code elsewhere in Firecrown does not use it incorrectly. We will then fix whatever needs fixing as a result, introduce a change to make sure the returned array is monotonically increasing, and then a new release of Firecrown for use by Augur.
